version: '3'
prom_graf:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
    - prom_graf      
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
    - prom_graf

networks:
  prom_graf:
    external:
      name: prom_graf
