global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'netdata-prometheus-grafana'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'netdata'
    # This is API endpoint for Netdata 
    metrics_path: /api/v1/allmetrics
    params:
      format: [ prometheus ]

    static_configs:
    # - targets: ['IPorHostname:Port','...', etc.]
    #   labels: 'SomeLabelForGrafana'
      - targets: ['london.my-netdata.io:80']
        labels: 
          demo-netdata-london: label
      - targets: ['frankfurt.my-netdata.io:80']
        labels: 
          demo-netdata-frankfurt: label
